env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - airbnb-base
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules:
  import/extensions: 0
  no-console: 0
  "react/prop-types": "off"
settings:
  react:
    createClass: createReactClass
    pragma: React
    fragment: Fragment
    version: detect
    flowVersion: '0.53'
  propWrapperFunctions:
    - forbidExtraProps
    - property: freeze
      object: Object
    - property: myFavoriteWrapper
    - property: forbidExtraProps
      exact: true
  componentWrapperFunctions:
    - observer
    - property: styled
    - property: observer
      object: Mobx
    - property: observer
      object: <pragma>
  formComponents:
    - CustomForm
    - name: Form
      formAttribute: endpoint
  linkComponents:
    - Hyperlink
    - name: Link
      linkAttribute: to
